name = "StatisticalTraits"
uuid = "64bff920-2084-43da-a3e6-9bb72801c0c9"
authors = ["Anthony D. Blaom <anthony.blaom@gmail.com>"]
version = "3.4.0"

[deps]
ScientificTypesBase = "30f210dd-8aff-4c5f-94ba-8e64358c1161"

[compat]
ScientificTypesBase = "1, 2, 3"
julia = "^1"

[extras]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SparseArrays"]
